#ifndef MOCKOS_CONSTANTS_H
#define MOCKOS_CONSTANTS_H

enum error_code {
    SUCCESS,
    INVALID_IMAGE,
    SIZE_MISMATCH,
    APPEND_NOT_SUPPORTED,
    FILE_ALREADY_EXISTS,
    FILE_IS_NULL,
    INVALID_FILE_TYPE,
    FILE_NOT_OPEN,
    FILE_DOES_NOT_EXIST,
    FILE_IS_OPEN,
};

#endif //MOCKOS_CONSTANTS_H